controller_list:
  - name: fake_Chain_controller
    type: $(arg fake_execution_type)
    joints:
      - Revolute 1
      - Revolute 2
      - Revolute 3
      - Revolute 4
initial:  # Define initial robot poses per group
  - group: Chain
    pose: pose_1